-- AlterTable
ALTER TABLE "PlayerStats" ADD COLUMN     "hpRegenPerMin" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "lastRegenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "spRegenPerMin" INTEGER NOT NULL DEFAULT 100;
